# WelcomeTitle
# By ZeBigDipper
# Version 1.0
# Please use the technical names of the colors.
# http://minecraft.gamepedia.com/Formatting_codes

Welcome Title: "Welcome To:"
Welcome Subtitle: "My Server"
Title Color: "gold"
Subtitle Color: "aqua"